name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2
      with:
        server_ip: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT}}
        script: |
          cd /var/www/html/relist-car
          git pull origin main
          git status
          npm install --only=prod
          pm2 restart relist
