# File: .github/workflows/ci-cd.yml

name: CI/CD with Express and PM2

on:
  push:
    branches:
      - main  # Ganti dengan nama branch utama Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm test

      - name: Deploy with PM2
        run: |
          npm install pm2 -g
          pm2 reload ecosystem.config.js --env production
